export enum TemplateNoteEnum {
  DEAL = "DEAL",
  WORK_PACKAGE = "WORK_PACKAGE",
  TECHNICAL_CONTEXT = "TECHNICAL_CONTEXT",
  PROJECT_COMMUNICATION_CONTACT = "PROJECT_COMMUNICATION_CONTACT",
  INTERNAL_NOTE = "INTERNAL_NOTE"
}